// <auto-generated />
using System;
using CompanyWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyWebApi.Migrations
{
    [DbContext(typeof(EmployeesContext))]
    [Migration("20230321095302_MyFirstMigration")]
    partial class MyFirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyWebApi.Entities.Employee", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("IDNumber")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1995, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Email = "sammy@companywebapi.com",
                            EmployeeNumber = 1,
                            FirstName = "Samuel",
                            Gender = 0,
                            IDNumber = 23049700,
                            JobTitle = "Software Developer",
                            JoinedDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kirigha",
                            MaritalStatus = 1,
                            PhoneNumber = "09776573458"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1999, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Email = "john@companywebapi.com",
                            EmployeeNumber = 2,
                            FirstName = "John",
                            Gender = 0,
                            IDNumber = 230465800,
                            JobTitle = "Software Developer",
                            JoinedDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mwasho",
                            MaritalStatus = 1,
                            PhoneNumber = "0875667487"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1985, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            Email = "jane@companywebapi.com",
                            EmployeeNumber = 3,
                            FirstName = "Jane",
                            Gender = 1,
                            IDNumber = 23049700,
                            JobTitle = "Human Resource Manager",
                            JoinedDate = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wambui",
                            MaritalStatus = 0,
                            PhoneNumber = "07873274671"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1989, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            Email = "peter@companywebapi.com",
                            EmployeeNumber = 4,
                            FirstName = "Peter",
                            Gender = 0,
                            IDNumber = 23049700,
                            JobTitle = "Sales Manager",
                            JoinedDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kamau",
                            MaritalStatus = 1,
                            PhoneNumber = "076748624"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
